In [42]:
import numpy as np
import pandas as pd
import seaborn as sns
import statsmodels.api as smf
import statsmodels.formula.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant

In [43]:
auto = pd.read_csv('Price_Prediction.csv', na_values='?')
auto.head()

,symboling,normalized_losses,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0

In [44]:
auto.isna().sum()

symboling             0
normalized_losses    41
make                  0
fuel_type             0
aspiration            0
num_of_doors          2
body_style            0
drive_wheels          0
engine_location       0
wheel_base            0
length                0
width                 0
height                0
curb_weight           0
engine_type           0
num_of_cylinders      0
engine_size           0
fuel_system           0
bore                  4
stroke                4
compression_ratio     0
horsepower            2
peak_rpm              2
city_mpg              0
highway_mpg           0
price                 4
dtype: int64

In [45]:
auto1 = auto.dropna()

In [46]:
auto1.reset_index(inplace=True)

In [47]:
auto1.drop(columns='index', inplace=True)

C:\Users\Kavita manoj\AppData\Local\Temp\ipykernel_26936\1860072619.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  auto1.drop(columns='index', inplace=True)

In [48]:
autoQuant = auto1.drop(columns=['symboling', 'make', 'fuel_type', 'aspiration', 'num_of_doors', 'body_style', 'drive_wheels', 'engine_location', 'engine_type', 'num_of_cylinders', 'fuel_system', 'price'])

In [49]:
autoQuant

,normalized_losses,wheel_base,length,width,height,curb_weight,engine_size,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg
0,164.0,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,102.0,5500.0,24,30
1,164.0,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,115.0,5500.0,18,22
2,158.0,105.8,192.7,71.4,55.7,2844,136,3.19,3.40,8.5,110.0,5500.0,19,25
3,158.0,105.8,192.7,71.4,55.9,3086,131,3.13,3.40,8.3,140.0,5500.0,17,20
4,192.0,101.2,176.8,64.8,54.3,2395,108,3.50,2.80,8.8,101.0,5800.0,23,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,95.0,109.1,188.8,68.9,55.5,2952,141,3.78,3.15,9.5,114.0,5400.0,23,28
155,95.0,109.1,188.8,68.8,55.5,3049,141,3.78,3.15,8.7,160.0,5300.0,19,25
156,95.0,109.1,188.8,68.9,55.5,3012,173,3.58,2.87,8.8,134.0,5500.0,18,23
157,95.0,109.1,188.8,68.9,55.5,3217,145,3.01,3.40,23.0,106.0,4800.0,26,27
158,95.0,109.1,188.8,68.9,55.5,3062,141,3.78,3.15,9.5,114.0,5400.0,19,25

In [50]:
X1 = add_constant(autoQuant)
vif = pd.DataFrame()
vif['Features'] = X1.columns
vif['VIF'] = [variance_inflation_factor(X1.values, i) for i in range (len(X1.columns))]

In [51]:
vif

             Features          VIF
0               const  7058.380507
1   normalized_losses     1.559208
2          wheel_base     6.205108
3              length     8.256949
4               width     5.730235
5              height     2.693944
6         curb_weight    16.702143
7         engine_size     9.086919
8                bore     2.338467
9              stroke     1.483640
10  compression_ratio     2.522903
11         horsepower     7.198786
12           peak_rpm     1.953069
13           city_mpg    25.188350
14        highway_mpg    22.830928

In [52]:
X1.drop(columns='city_mpg', inplace=True)
vif = pd.DataFrame()
vif['Features'] = X1.columns
vif['VIF'] = [variance_inflation_factor(X1.values, i) for i in range (len(X1.columns))]
vif

             Features          VIF
0               const  6975.969097
1   normalized_losses     1.481003
2          wheel_base     6.120171
3              length     7.566817
4               width     5.724954
5              height     2.689368
6         curb_weight    16.684625
7         engine_size     9.062256
8                bore     2.322459
9              stroke     1.465905
10  compression_ratio     2.309051
11         horsepower     7.038740
12           peak_rpm     1.945452
13        highway_mpg     5.639093

In [53]:
X1.drop(columns='curb_weight', inplace=True)
vif = pd.DataFrame()
vif['Features'] = X1.columns
vif['VIF'] = [variance_inflation_factor(X1.values, i) for i in range (len(X1.columns))]
vif

             Features          VIF
0               const  6407.466203
1   normalized_losses     1.467556
2          wheel_base     6.008260
3              length     7.398795
4               width     5.491800
5              height     2.455693
6         engine_size     6.606965
7                bore     2.321820
8              stroke     1.437999
9   compression_ratio     1.960585
10         horsepower     6.651888
11           peak_rpm     1.943999
12        highway_mpg     5.088710

In [54]:
X1.drop(columns='length', inplace=True)
vif = pd.DataFrame()
vif['Features'] = X1.columns
vif['VIF'] = [variance_inflation_factor(X1.values, i) for i in range (len(X1.columns))]

In [62]:
auto1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          159 non-null    int64
 1   normalized_losses  159 non-null    float64
 2   make               159 non-null    object
 3   fuel_type          159 non-null    object
 4   aspiration         159 non-null    object
 5   num_of_doors       159 non-null    object
 6   body_style         159 non-null    object
 7   drive_wheels       159 non-null    object
 8   engine_location    159 non-null    object
 9   wheel_base         159 non-null    float64
 10  length             159 non-null    float64
 11  width              159 non-null    float64
 12  height             159 non-null    float64
 13  curb_weight        159 non-null    int64
 14  engine_type        159 non-null    object
 15  num_of_cylinders   159 non-null    object
 16  engine_size        159 non-null    int64
 17  fuel_system        159 non-null    object
 18  bore               159 non-null    float64
 19  stroke             159 non-null    float64
 20  compression_ratio  159 non-null    float64
 21  horsepower         159 non-null    float64
 22  peak_rpm           159 non-null    float64
 23  city_mpg           159 non-null    int64
 24  highway_mpg        159 non-null    int64
 25  price              159 non-null    float64
dtypes: float64(11), int64(5), object(10)
memory usage: 32.4+ KB

In [56]:
fit1 = sm.ols('price~width+engine_size+stroke+compression_ratio+horsepower', data=auto1).fit()

In [57]:
fit1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.819
Model:                            OLS   Adj. R-squared:                  0.813
Method:                 Least Squares   F-statistic:                     138.6
Date:                Tue, 28 Mar 2023   Prob (F-statistic):           5.97e-55
Time:                        21:14:36   Log-Likelihood:                -1469.1
No. Observations:                 159   AIC:                             2950.
Df Residuals:                     153   BIC:                             2969.
Df Model:                           5
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept         -7.545e+04    1.1e+04     -6.881      0.000   -9.71e+04   -5.38e+04
width              1192.1699    179.235      6.651      0.000     838.076    1546.264
engine_size          67.1419     14.343      4.681      0.000      38.806      95.478
stroke            -1707.6932    741.338     -2.304      0.023   -3172.274    -243.113
compression_ratio   178.0656     64.864      2.745      0.007      49.921     306.211
horsepower           45.8836     13.447      3.412      0.001      19.317      72.450
==============================================================================
Omnibus:                       10.438   Durbin-Watson:                   0.797
Prob(Omnibus):                  0.005   Jarque-Bera (JB):               10.656
Skew:                           0.561   Prob(JB):                      0.00485
Kurtosis:                       3.592   Cond. No.                     9.32e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.32e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [59]:
auto2 = pd.DataFrame()
auto2.insert(0, column='width', value=auto1.width)
auto2.insert(1, column='engine_size', value=auto1.engine_size)
auto2.insert(2, column='stroke', value=auto1.stroke)
auto2.insert(3, column='compression_ratio', value=auto1.compression_ratio)
auto2.insert(4, column='horsepower', value=auto1.horsepower)
auto2.insert(5, column='price', value=auto.price)
auto2

     width  engine_size  stroke  compression_ratio  horsepower    price
0     66.2          109    3.40               10.0       102.0  13495.0
1     66.4          136    3.40                8.0       115.0  16500.0
2     71.4          136    3.40                8.5       110.0  16500.0
3     71.4          131    3.40                8.3       140.0  13950.0
4     64.8          108    2.80                8.8       101.0  17450.0
..     ...          ...     ...                ...         ...      ...
154   68.9          141    3.15                9.5       114.0   7898.0
155   68.8          141    3.15                8.7       160.0   8778.0
156   68.9          173    2.87                8.8       134.0   6938.0
157   68.9          145    3.40               23.0       106.0   7198.0
158   68.9          141    3.15                9.5       114.0   7898.0

[159 rows x 6 columns]

In [67]:
ohe = pd.get_dummies(data=auto1,  columns=['make', 'fuel_type', 'aspiration', 'num_of_doors', 'body_style', 'drive_wheels', 'engine_location', 'engine_type', 'num_of_cylinders', 'fuel_system'])

In [70]:
ohe.drop(columns=['normalized_losses', 'wheel_base', 'length', 'height', 'curb_weight', 'bore', 'peak_rpm', 'city_mpg', 'highway_mpg'], inplace=True)

In [71]:
ohe

,symboling,width,engine_size,stroke,compression_ratio,horsepower,price,make_audi,make_bmw,make_chevrolet,...,num_of_cylinders_five,num_of_cylinders_four,num_of_cylinders_six,num_of_cylinders_three,fuel_system_1bbl,fuel_system_2bbl,fuel_system_idi,fuel_system_mfi,fuel_system_mpfi,fuel_system_spdi
0,2,66.2,109,3.40,10.0,102.0,13950.0,1,0,0,...,0,1,0,0,0,0,0,0,1,0
1,2,66.4,136,3.40,8.0,115.0,17450.0,1,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,71.4,136,3.40,8.5,110.0,17710.0,1,0,0,...,1,0,0,0,0,0,0,0,1,0
3,1,71.4,131,3.40,8.3,140.0,23875.0,1,0,0,...,1,0,0,0,0,0,0,0,1,0
4,2,64.8,108,2.80,8.8,101.0,16430.0,0,1,0,...,0,1,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,-1,68.9,141,3.15,9.5,114.0,16845.0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
155,-1,68.8,141,3.15,8.7,160.0,19045.0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
156,-1,68.9,173,2.87,8.8,134.0,21485.0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
157,-1,68.9,145,3.40,23.0,106.0,22470.0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
158,-1,68.9,141,3.15,9.5,114.0,22625.0,0,0,0,...,0,1,0,0,0,0,0,0,1,0

In [72]:
ohe.columns

Index(['symboling', 'width', 'engine_size', 'stroke', 'compression_ratio',
       'horsepower', 'price', 'make_audi', 'make_bmw', 'make_chevrolet',
       'make_dodge', 'make_honda', 'make_jaguar', 'make_mazda',
       'make_mercedes-benz', 'make_mitsubishi', 'make_nissan', 'make_peugot',
       'make_plymouth', 'make_porsche', 'make_saab', 'make_subaru',
       'make_toyota', 'make_volkswagen', 'make_volvo', 'fuel_type_diesel',
       'fuel_type_gas', 'aspiration_std', 'aspiration_turbo',
       'num_of_doors_four', 'num_of_doors_two', 'body_style_convertible',
       'body_style_hardtop', 'body_style_hatchback', 'body_style_sedan',
       'body_style_wagon', 'drive_wheels_4wd', 'drive_wheels_fwd',
       'drive_wheels_rwd', 'engine_location_front', 'engine_type_dohc',
       'engine_type_l', 'engine_type_ohc', 'engine_type_ohcf',
       'engine_type_ohcv', 'num_of_cylinders_eight', 'num_of_cylinders_five',
       'num_of_cylinders_four', 'num_of_cylinders_six',
       'num_of_cylinders_three', 'fuel_system_1bbl', 'fuel_system_2bbl',
       'fuel_system_idi', 'fuel_system_mfi', 'fuel_system_mpfi',
       'fuel_system_spdi'],
      dtype='object')

In [113]:
fit2 = sm.ols('price~engine_size+ make_audi+ make_bmw+ make_chevrolet+make_dodge+ make_honda+ make_mazda+ make_mitsubishi+ make_nissan+ make_peugot+make_plymouth+ make_saab+ make_subaru+make_toyota+ make_volkswagen+ make_volvo+ fuel_type_diesel+fuel_type_gas+ aspiration_turbo+num_of_doors_four+ num_of_doors_two+ body_style_convertible+drive_wheels_rwd+ engine_location_front+ engine_type_ohcf+num_of_cylinders_four+ fuel_system_1bbl+fuel_system_idi', data=ohe).fit()

In [114]:
fit2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.953
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     118.8
Date:                Tue, 28 Mar 2023   Prob (F-statistic):           4.90e-78
Time:                        21:36:47   Log-Likelihood:                -1362.1
No. Observations:                 159   AIC:                             2772.
Df Residuals:                     135   BIC:                             2846.
Df Model:                          23
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept               4161.7896    485.773      8.567      0.000    3201.079    5122.500
engine_size               57.9075      7.749      7.473      0.000      42.582      73.233
make_audi              -3466.4468   1072.652     -3.232      0.002   -5587.822   -1345.072
make_bmw               -3745.1482    991.490     -3.777      0.000   -5706.010   -1784.287
make_chevrolet         -1.042e+04   1220.289     -8.541      0.000   -1.28e+04   -8008.589
make_dodge             -1.011e+04    951.311    -10.632      0.000    -1.2e+04   -8233.399
make_honda             -5882.3282   1265.840     -4.647      0.000   -8385.771   -3378.885
make_mazda             -8686.5146    892.587     -9.732      0.000   -1.05e+04   -6921.252
make_mitsubishi        -1.035e+04    924.978    -11.190      0.000   -1.22e+04   -8521.382
make_nissan            -9451.7844    808.560    -11.690      0.000   -1.11e+04   -7852.701
make_peugot            -7423.8782    871.414     -8.519      0.000   -9147.267   -5700.489
make_plymouth          -1.037e+04    996.441    -10.405      0.000   -1.23e+04   -8397.546
make_saab              -3965.6060    974.548     -4.069      0.000   -5892.962   -2038.250
make_subaru            -4804.8334    447.313    -10.742      0.000   -5689.482   -3920.185
make_toyota            -9719.3055    756.506    -12.848      0.000   -1.12e+04   -8223.170
make_volkswagen        -8547.8889    905.156     -9.444      0.000   -1.03e+04   -6757.769
make_volvo             -5982.1997    811.199     -7.375      0.000   -7586.501   -4377.899
fuel_type_diesel         989.8016    208.518      4.747      0.000     577.417    1402.186
fuel_type_gas           3171.9880    388.007      8.175      0.000    2404.629    3939.347
aspiration_turbo        3073.8857    364.693      8.429      0.000    2352.636    3795.135
num_of_doors_four       2641.2370    282.017      9.366      0.000    2083.493    3198.981
num_of_doors_two        1520.5526    273.747      5.555      0.000     979.164    2061.941
body_style_convertible  6052.8413   1071.439      5.649      0.000    3933.865    8171.817
drive_wheels_rwd        2360.2449    532.544      4.432      0.000    1307.038    3413.452
engine_location_front   4161.7896    485.773      8.567      0.000    3201.079    5122.500
engine_type_ohcf       -4804.8334    447.313    -10.742      0.000   -5689.482   -3920.185
num_of_cylinders_four  -2418.9598    554.857     -4.360      0.000   -3516.297   -1321.623
fuel_system_1bbl       -3204.8936   1064.866     -3.010      0.003   -5310.871   -1098.916
fuel_system_idi          989.8016    208.518      4.747      0.000     577.417    1402.186
==============================================================================
Omnibus:                        8.019   Durbin-Watson:                   1.830
Prob(Omnibus):                  0.018   Jarque-Bera (JB):               15.520
Skew:                          -0.010   Prob(JB):                     0.000426
Kurtosis:                       4.530   Cond. No.                     4.38e+18
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.26e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""